---
  driver:
    name: docker
    remove_images: true
    privileged: true
    ssh_host: 172.17.0.1
    volume:
      - /var/run/docker.sock:/var/run/docker.sock

  platforms:
    - name: ib-toolbox
      driver_config:
        image: debian:stable-slim
        platform: debian

  provisioner:
    name: chef_zero
    always_update_cookbooks: true

  verifier:
    name: inspec

  suites:
    - name: integration
      run_list:
        - recipe[ib-toolbox]
      verifier:
        inspec_tests:
          - test/integration
